- hosts: all
  gather_facts: no
  tasks:
        - name: creating a directory
          file:
                path: ~/testdir
                state: directory
          tags:
                directory
  
        - name: creating a directory3
          file:
                path: ~/testdir3
                state: directory
        - name: creating a directory2
          file:
                path: ~/testdir2
                state: directory
          tags:
                directory2 
        - name: installing tomcat 
          package:
                 name: tomcat8
                 state: present
          become: yes
          tags: 
                 tomcat 
