- hosts: all
  strategy: free
  tasks:
          - name: installing tomcat 
            package:
                 name: tomcat8
                 state: present
            become: yes
            tags: 
                 tomcat 
